### ISSUE TITLE
Ninja build fails on windows

### ISSUE THREAD

**Issue by boxerab** [centricular/cairo#4]
`\libpng-1.6.34\pngtest.c(73): fatal error C1083: Cannot open include file: 'zlib.h'`

**Comment by boxerab** [comment]
btw, I am pointing my `PKG_CONFIG_PATH` environment variable to the gstreamer `pkgconfig` folder generated by gst-build, so meson does pick up the zlib .pc file from there.

**Comment by boxerab** [comment]
meson log file:

[meson-log.txt](https://github.com/centricular/cairo/files/3414084/meson-log.txt)

**Comment by tp-m** [comment]
> btw, I am pointing my `PKG_CONFIG_PATH` environment variable to the gstreamer `pkgconfig` folder generated by gst-build, so meson does pick up the zlib .pc file from there.

I don't understand what you mean by this. It sounds like a very strange setup. What is your `PKG_CONFIG_PATH` exactly?

**Comment by boxerab** [comment]
Thanks, my setup is:

1. running gst-build , with install prefix `GST_ROOT`
1. `%PKG_CONFIG_PATH% = %GST_ROOT%\lib\pkgconfig`

so pretty simple setup.

**Comment by tp-m** [comment]
Actually, this fails to build in `libpng`. Have you tried building just libpng by itself? I don't think this has anything to do with the cairo module, but it's probably a bug in libpng's `meson.build` file somewhere (probably a missing dep).

**Comment by tp-m** [comment]
You could try this, maybe it helps: https://github.com/tp-m/cairo/commit/3c363288617b654514c18d5e35da3d258a54dda3

**Comment by boxerab** [comment]
Beautiful - thanks!

**Comment by boxerab** [comment]
Yes, this worked for me.
